version: "3.8"

services:
  user-service:
    image: youssefamr705/user-service:latest
    ports:
      - 5000:5000
    environment:
      - MONGO_URI=${MONGO_URI_USERS}
      - JWT_SECRET=${JWT_SECRET}
    networks:
      - ecommerce-network
    depends_on:
      - mongo
    deploy:
      replicas: 2

  product-service:
    image: youssefamr705/product-service:latest
    ports:
      - 5001:5001
    environment:
      - MONGO_URI=${MONGO_URI_PRODUCTS}
    networks:
      - ecommerce-network
    depends_on:
      - mongo
    deploy:
      replicas: 2

  shopping-cart-service:
    image: youssefamr705/shopping-cart-service:latest
    ports:
      - 5002:5002
    environment:
      - MONGO_URI=${MONGO_URI_CART}
    networks:
      - ecommerce-network
    depends_on:
      - mongo
    deploy:
      replicas: 2

  order-service:
    image: youssefamr705/order-service:latest
    ports:
      - 5003:5003
    environment:
      - MONGO_URI=${MONGO_URI_ORDER}
    networks:
      - ecommerce-network
    depends_on:
      - mongo
    deploy:
      replicas: 2

  payment-service:
    image: youssefamr705/payment-service:latest
    ports:
      - 5004:5004
    environment:
      - MONGO_URI=${MONGO_URI_PAYMENT}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
    networks:
      - ecommerce-network
    depends_on:
      - mongo
    deploy:
      replicas: 2

  notification-service:
    image: youssefamr705/notification-service:latest
    ports:
      - 5005:5005
    environment:
      - NODEMAILER_EMAIL=${NODEMAILER_EMAIL}
      - NODEMAILER_PASSWORD=${NODEMAILER_PASSWORD}
      - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
      - TWILIO_PHONE_NUMBER=${TWILIO_PHONE_NUMBER}
    networks:
      - ecommerce-network

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - ecommerce-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    # Using Swarm configs instead of a local volume mount
    configs:
      - source: nginx_config
        target: /etc/nginx/nginx.conf
    networks:
      - ecommerce-network
    depends_on:
      - user-service
      - product-service
      - shopping-cart-service
      - order-service
      - payment-service

volumes:
  mongo-data:

# Define the config object Swarm will distribute to the Nginx containers
configs:
  nginx_config:
    file: ./nginx.conf

networks:
  ecommerce-network:
    driver: overlay # Crucial for multi-node Docker Swarm communication